package model

import (
	"time"
)

// ReviewRequest represents a code review request
type ReviewRequest struct {
	ProjectID    string
	MergeRequest *MergeRequest
	Changes      []*FileDiff
	CommitSHA    string
}

// MergeRequest represents a merge/pull request across different providers
type MergeRequest struct {
	ID           string
	IID          int
	Title        string
	Description  string
	SourceBranch string
	TargetBranch string
	AuthorID     string
	Author       *User
	Reviewers    []*User
	URL          string
	State        string
	SHA          string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// FileDiff represents changes in a single file
type FileDiff struct {
	OldPath     string
	NewPath     string
	Diff        string
	IsNew       bool
	IsDeleted   bool
	IsRenamed   bool
	IsBinary    bool
	ContentType string
}

// User represents a user across different providers
type User struct {
	ID       string
	Username string
	Name     string
	Email    string
}

// ReviewComment represents a code review comment
type ReviewComment struct {
	ID       string
	Body     string
	FilePath string
	Line     int
	Author   *User
}

// CodeEvent represents a webhook event from any provider
type CodeEvent struct {
	Type         string
	Action       string
	ProjectID    string
	MergeRequest *MergeRequest
	Comment      *Comment
	User         *User
	Timestamp    time.Time
}

// Comment represents a comment on a merge request or a reply to a comment
type Comment struct {
	ID        string
	Body      string
	AuthorID  string
	Author    *User
	FilePath  string
	Line      int
	ParentID  string // For threaded comments/replies
	IsReply   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// AIGeneratedContent represents content generated by AI
type AIGeneratedContent struct {
	Description    string
	ReviewComments []*ReviewComment
	Summary        string
}

// ReviewResult represents the result of a code review process
type ReviewResult struct {
	Success            bool
	ProcessedFiles     int
	CommentsCreated    int
	DescriptionUpdated bool
	Errors             []error
}

// FileFilter represents criteria for filtering files to review
type FileFilter struct {
	MaxFileSize       int
	AllowedExtensions []string
	ExcludedPaths     []string
	IncludeOnlyCode   bool
}

// MergeRequestFilter represents criteria for filtering merge requests
type MergeRequestFilter struct {
	State        []string   // e.g., "open", "closed", "merged"
	AuthorID     string     // Filter by author
	TargetBranch string     // Filter by target branch
	SourceBranch string     // Filter by source branch
	UpdatedAfter *time.Time // Filter by last update time
	CreatedAfter *time.Time // Filter by creation time
	Limit        int        // Maximum number of results (0 = no limit)
	Page         int        // Page number for pagination (0-based)
}

// ProviderConfig represents provider-specific configuration
type ProviderConfig struct {
	BaseURL       string
	Token         string
	WebhookSecret string
	BotUsername   string
}
