server:
  address: ":8080"
  endpoint: "/webhook"
  timeout: 30s

provider:
  type: "github"
  base_url: "https://github.com"  

agent:
  type: "gemini"
  model: "gemini-2.5-flash"  


review:
  verbose: true

  generate:
    description: true
    changes_overview: true
    architecture: true
    code: true

  scoring:
    mode: "everything"

  filter:
    allowed_extensions:
      - ".go"
      - ".js"
      - ".ts"
      - ".py"
      - ".yaml"
      - ".yml"
      - ".sql"
      - ".md"
      - ".dockerfile"
      - ".sh"
    excluded_paths:
      - "vendor"
      - "node_modules"
      - "dist"
      - "build"
      - "target"
