version: '3.6'

services:
  mr-reviewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mr-reviewer
    restart: always
    volumes:
      - ./config.yaml:/etc/config.yaml
    ports:
      - 8080:8080
    command:
      - "--config"
      - "/etc/config.yaml"
